# Generated by Django 5.2.7 on 2025-11-13 07:28

import assets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('property', 'Property'), ('business', 'Business'), ('vehicle', 'Vehicle'), ('products', 'Products'), ('contracts', 'Contracts'), ('money', 'Money')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('insured', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to=assets.models.user_avatar_upload_path, verbose_name='Asset Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
