# Generated by Django 5.2.7 on 2025-11-13 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('owner', 'name', 'type', 'value')},
        ),
    ]
