# Generated by Django 5.2.7 on 2025-11-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('name', 'type', 'value')},
        ),
    ]
